version: "3"

services:

    php-fpm:
        build: ./Dockerfiles/php-fpm
        working_dir: /var/www/
        container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}php-fpm"
        ports:
            - ${PHP_FPM_HOST_PORT}:${PHP_FPM_CONTAINER_PORT}
        volumes:
            - ./Symfony:/var/www/
    apache:
        build: ./Dockerfiles/webserver
        container_name: symfony-apache
        volumes:
            - ./Apache:/etc/apache2/sites-enabled
            - ./Symfony:/var/www/
        ports:
            - ${APACHE_HOST_PORT}:${APACHE_CONTAINER_PORT}
    mysql:
        image:  mysql:5.7
        container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}mysql"
        environment:
            MYSQL_ROOT_PASSWORD: pasforsymfony
            MYSQL_DATABASE: pasforsymfony
            MYSQL_USER: pasforsymfony
            MYSQL_PASSWORD: pasforsymfony
        volumes:
            - ./Mysql/data/mysql:/var/lib/mysql
            - ./Logs/mysql:/var/log/mysql
        ports:
            - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_VOLUME}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${PROJECT_NAME}${PROJECT_SEPARATOR}phpmyadmin"
        environment:
          PMA_HOST: "${PROJECT_NAME}${PROJECT_SEPARATOR}mysql"
          PMA_PORT: 3306
        ports:
            - ${PHPMYADMIN_HOST_PORT}:${PHPMYADMIN_CONTAINER_PORT}